version: '3'
services: 
    angular:
        image: miraj/angular
        container_name: miraj-angular
        build: 
            context: .
        volumes:
          - .:/app
          - node_modules:/app/node_modules
        ports:
          - "4200:4200"

volumes: 
    node_modules: